dist: bionic

language: php

sudo: false

php:
  - 7.3
  - 7.4
  - 8

git:
  depth: 1

matrix:
  fast_finish: true

before_install:
  # Disable XDebug to speed up execution.
  - phpenv config-rm xdebug.ini
  # phantomjs is only needed for JS tests.
  - phantomjs --version;
  - export PATH=$HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH;
  - phantomjs --version;
  - if [[ $(phantomjs --version) != '2.1.1' ]]; then rm -rf $HOME/travis_phantomjs; mkdir -p $HOME/travis_phantomjs; wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; tar -xvf $HOME/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $HOME/travis_phantomjs; fi;
  - phantomjs --version
  # Always update Composer to the recent version, otherwise the drush
  # installation fails.
  #- composer selfupdate --stable

install:
  # Add composer's global bin directory to the path.
  #- export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install drush globally
  #- composer global require drush/drush:$DRUSH_VERSION
  #- composer global require drupal/coder:$CODER_VERSION
  - npm install
  - npm install -g gulp
  - gulp build

before_script:
  - cp -r src/app/tests dist/app/tests 


script:
  # PHP lint
  - >
    echo;
    echo "Running PHP lint";
    phpunit --exclude-group=no-ci;